### ISSUE TITLE
Data file(s)

### ISSUE THREAD

**Issue by SmithersA** [GSA/sdg-indicators#914] opened 2018-05-08 14:37 UTC
@brockfanning Does the French translation need the following file?
sdg-indicators/data/es/sdg_goals.csv

If yes, re-assign to me and I can duplicate the file. 
If so, does the Spanish version need to be finished also? Only goals 1 - 7 are translated.

**Comment by brockfanning** [comment] 2018-05-09 11:10
@SmithersA Yes, I believe, to both questions.

**Comment by SmithersA** [comment] 2018-05-21 14:05
https://github.com/GSA/sdg-indicators/blob/gh-pages/data/fr/sdg_goals.csv
Column 3 remains to be translated 
and sdg_indicator_metadata.csv remains to be created in https://github.com/GSA/sdg-indicators/blob/gh-pages/data/fr/

**Comment by philipashlock** [comment] 2018-07-26 22:02
I'm closing this as a duplicate of #915

**Closed by philipashlock** 2018-07-26 22:02 UTC
Labels: French
